#!/usr/bin/env bash

DEBUG="false"

ENV_FILES="env"
MAC_ENV_FILES="env_mac"

POSIX_FILES="aliases functions"
MAC_FILES="aliases_mac functions_mac"

# TODO: get rid of "git-prompt"? the prompt stuff works w/ whatever's in "git"
#EXTRAS="functions_vcs git git-prompt aliases_git"
EXTRAS="functions_vcs git aliases_git"

FILES_TO_SOURCE="$ENV_FILES $POSIX_FILES"

if [[ "$OSTYPE" == darwin* ]]; then
	FILES_TO_SOURCE="$ENV_FILES $MAC_ENV_FILES $POSIX_FILES $MAC_FILES"
fi

FILES_TO_SOURCE="$FILES_TO_SOURCE $EXTRAS"
$DEBUG && echo "files to source: [$FILES_TO_SOURCE]"

BASE="`dirname $BASH_SOURCE`/jibberia_bash"
$DEBUG && echo "base: [$BASE]"

if [[ -d "$BASE" ]]; then
	for FILE in $FILES_TO_SOURCE; do
		FILE="$BASE/$FILE.sh"
        $DEBUG && echo "sourcing $FILE"
        source "$FILE"
	done
	unset FILE
else
	echo "************************************"
	echo "** unable to source jibberia_bash **"
	echo "************************************"
fi

unset ENV_FILES MAC_ENV_FILES POSIX_FILES MAC_FILES ENV_FILES EXTRAS FILES_TO_SOURCE BASE DEBUG

if which fortune &> /dev/null; then
	fortune -a
fi
