#!/usr/bin/env bash

DEBUG="true"

POSIX_FILES="env aliases functions"
MAC_FILES="env_mac aliases_mac functions_mac"
EXTRAS="functions_vcs"

FILES_TO_SOURCE="$POSIX_FILES"

if [[ "$OSTYPE" == darwin* ]]; then
	FILES_TO_SOURCE="$FILES_TO_SOURCE $MAC_FILES"
fi

FILES_TO_SOURCE="$FILES_TO_SOURCE $MAC_FILES $EXTRAS"
$DEBUG && echo "files to source: [$FILES_TO_SOURCE]"

BASE="`dirname $BASH_SOURCE`/jibberia_bash"
$DEBUG && echo "base: [$BASE]"

if [[ -d "$BASE" ]]; then

	for FILE in $FILES_TO_SOURCE; do
		# $DEBUG && echo "$FILE"
		FILE="$BASE/$FILE.sh"
		if [[ -x "$FILE" && ! -d "$FILE" ]]; then
			$DEBUG && echo "sourced $FILE"
			source "$FILE"
		else
			$DEBUG && echo "*** COULD NOT SOURCE [$FILE]"
		fi
	done
else
	echo "************************************"
	echo "** unable to source jibberia_bash **"
	echo "************************************"
fi

if which fortune &> /dev/null; then
	fortune -a
fi

