#!/usr/bin/env bash

DEBUG="false"

ENV_FILES="env"
MAC_ENV_FILES="env_mac"

POSIX_FILES="aliases functions"
MAC_FILES="aliases_mac functions_mac"

EXTRAS="functions_vcs git git-prompt aliases_git"

FILES_TO_SOURCE="$ENV_FILES $POSIX_FILES"

if [[ "$OSTYPE" == darwin* ]]; then
	FILES_TO_SOURCE="$ENV_FILES $MAC_ENV_FILES $POSIX_FILES $MAC_FILES"
fi

FILES_TO_SOURCE="$FILES_TO_SOURCE $EXTRAS"
$DEBUG && echo "files to source: [$FILES_TO_SOURCE]"

BASE="`dirname $BASH_SOURCE`/jibberia_bash"
$DEBUG && echo "base: [$BASE]"

if [[ -d "$BASE" ]]; then
	for FILE in $FILES_TO_SOURCE; do
		# $DEBUG && echo "$FILE"
		FILE="$BASE/$FILE.sh"
		if [[ -x "$FILE" && ! -d "$FILE" ]]; then
			$DEBUG && echo "sourced $FILE"
			source "$FILE"
		else
			$DEBUG && echo "*** COULD NOT SOURCE [$FILE]"
		fi
	done
	unset FILE
else
	echo "************************************"
	echo "** unable to source jibberia_bash **"
	echo "************************************"
fi

unset ENV_FILES MAC_ENV_FILES POSIX_FILES MAC_FILES ENV_FILES EXTRAS FILES_TO_SOURCE BASE DEBUG

if which fortune &> /dev/null; then
	fortune -a
fi
