syn on

set autoindent
set smartindent
"set wrap
set expandtab
set smarttab
set tabstop=4
set shiftwidth=4
set softtabstop=4

filetype indent plugin on
" disable 'new line continues comment' behavior
autocmd FileType * setlocal formatoptions-=c formatoptions-=r formatoptions-=o

set wildmenu

set ignorecase
set smartcase

set incsearch
set hlsearch

" always show status bar:
"set laststatus=2

" Commenting blocks of code.
autocmd FileType c,cpp,java,scala let b:comment_leader = '// '
autocmd FileType sh,ruby,python   let b:comment_leader = '# '
autocmd FileType conf,fstab       let b:comment_leader = '# '
autocmd FileType tex              let b:comment_leader = '% '
autocmd FileType mail             let b:comment_leader = '> '
autocmd FileType vim              let b:comment_leader = '" '
noremap <silent> ,cc :<C-B>silent <C-E>s/^/<C-R>=escape(b:comment_leader,'\/')<CR>/<CR>:nohlsearch<CR>
noremap <silent> ,cu :<C-B>silent <C-E>s/^\V<C-R>=escape(b:comment_leader,'\/')<CR>//e<CR>:nohlsearch<CR>

" 2-space indents for ruby
autocmd Filetype ruby setlocal ts=2 sts=2 sw=2
